### ISSUE TITLE
Drawing class(es) need to include support for bounding box.

### ISSUE THREAD

**Issue by theminima** [FlubDubStubs/PurpleAmerica#11]
When reading in data, the InputParser gets information about the max and min latitudes and longitudes.  This data can be used to determine the size and scale of the drawing window.  
![boundingbox](https://cloud.githubusercontent.com/assets/18404851/15215914/d5bc7490-1822-11e6-9c00-682b36f6c7de.PNG)

These methods will return the min and max coordinates so you can easily get that data using the InputParser class.

**Comment by theminima** [comment]
@hcps-mabrysh

**Comment by shmabry** [comment]
I've added a bounding box with the max and min values you gave me.

**Comment by NoahKamencik** [comment]
What can I do for you guys tonight?

**Comment by hcps-mabrysh** [comment]
@NoahKamencik you and @theminima can figure out how to get the colors working because that is a big part of the project and we still don't have it done. @NoahKamencik make sure you make a method that is basically a getter for a color - all it does is returns the color you calculated.

**Comment by shmabry** [comment]
I've got bounding box coordinates.
